package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// noinspection SpellCheckingInspection
const (
	SoundEventItemUseOn = iota
	SoundEventHit
	SoundEventStep
	SoundEventFly
	SoundEventJump
	SoundEventBreak
	SoundEventPlace
	SoundEventHeavyStep
	SoundEventGallop
	SoundEventFall
	SoundEventAmbient
	SoundEventAmbientBaby
	SoundEventAmbientInWater
	SoundEventBreathe
	SoundEventDeath
	SoundEventDeathInWater
	SoundEventDeathToZombie
	SoundEventHurt
	SoundEventHurtInWater
	SoundEventMad
	SoundEventBoost
	SoundEventBow
	SoundEventSquishBig
	SoundEventSquishSmall
	SoundEventFallBig
	SoundEventFallSmall
	SoundEventSplash
	SoundEventFizz
	SoundEventFlap
	SoundEventSwim
	SoundEventDrink
	SoundEventEat
	SoundEventTakeoff
	SoundEventShake
	SoundEventPlop
	SoundEventLand
	SoundEventSaddle
	SoundEventArmor
	SoundEventArmorPlace
	SoundEventAddChest
	SoundEventThrow
	SoundEventAttack
	SoundEventAttackNoDamage
	SoundEventAttackStrong
	SoundEventWarn
	SoundEventShear
	SoundEventMilk
	SoundEventThunder
	SoundEventExplode
	SoundEventFire
	SoundEventIgnite
	SoundEventFuse
	SoundEventStare
	SoundEventSpawn
	SoundEventShoot
	SoundEventBreakBlock
	SoundEventLaunch
	SoundEventBlast
	SoundEventLargeBlast
	SoundEventTwinkle
	SoundEventRemedy
	SoundEventUnfect
	SoundEventLevelUp
	SoundEventBowHit
	SoundEventBulletHit
	SoundEventExtinguishFire
	SoundEventItemFizz
	SoundEventChestOpen
	SoundEventChestClosed
	SoundEventShulkerBoxOpen
	SoundEventShulkerBoxClosed
	SoundEventEnderChestOpen
	SoundEventEnderChestClosed
	SoundEventPowerOn
	SoundEventPowerOff
	SoundEventAttach
	SoundEventDetach
	SoundEventDeny
	SoundEventTripod
	SoundEventPop
	SoundEventDropSlot
	SoundEventNote
	SoundEventThorns
	SoundEventPistonIn
	SoundEventPistonOut
	SoundEventPortal
	SoundEventWater
	SoundEventLavaPop
	SoundEventLava
	SoundEventBurp
	SoundEventBucketFillWater
	SoundEventBucketFillLava
	SoundEventBucketEmptyWater
	SoundEventBucketEmptyLava
	SoundEventEquipChain
	SoundEventEquipDiamond
	SoundEventEquipGeneric
	SoundEventEquipGold
	SoundEventEquipIron
	SoundEventEquipLeather
	SoundEventEquipElytra
	SoundEventRecord13
	SoundEventRecordCat
	SoundEventRecordBlocks
	SoundEventRecordChirp
	SoundEventRecordFar
	SoundEventRecordMall
	SoundEventRecordMellohi
	SoundEventRecordStal
	SoundEventRecordStrad
	SoundEventRecordWard
	SoundEventRecord11
	SoundEventRecordWait
	SoundEventRecordNull
	SoundEventFlop
	SoundEventGuardianCurse
	SoundEventMobWarning
	SoundEventMobWarningBaby
	SoundEventTeleport
	SoundEventShulkerOpen
	SoundEventShulkerClose
	SoundEventHaggle
	SoundEventHaggleYes
	SoundEventHaggleNo
	SoundEventHaggleIdle
	SoundEventChorusGrow
	SoundEventChorusDeath
	SoundEventGlass
	SoundEventPotionBrewed
	SoundEventCastSpell
	SoundEventPrepareAttackSpell
	SoundEventPrepareSummon
	SoundEventPrepareWololo
	SoundEventFang
	SoundEventCharge
	SoundEventTakePicture
	SoundEventPlaceLeashKnot
	SoundEventBreakLeashKnot
	SoundEventAmbientGrowl
	SoundEventAmbientWhine
	SoundEventAmbientPant
	SoundEventAmbientPurr
	SoundEventAmbientPurreow
	SoundEventDeathMinVolume
	SoundEventDeathMidVolume
	SoundEventImitateBlaze
	SoundEventImitateCaveSpider
	SoundEventImitateCreeper
	SoundEventImitateElderGuardian
	SoundEventImitateEnderDragon
	SoundEventImitateEnderman
	SoundEventImitateEndermite
	SoundEventImitateEvocationIllager
	SoundEventImitateGhast
	SoundEventImitateHusk
	SoundEventImitateIllusionIllager
	SoundEventImitateMagmaCube
	SoundEventImitatePolarBear
	SoundEventImitateShulker
	SoundEventImitateSilverfish
	SoundEventImitateSkeleton
	SoundEventImitateSlime
	SoundEventImitateSpider
	SoundEventImitateStray
	SoundEventImitateVex
	SoundEventImitateVindicationIllager
	SoundEventImitateWitch
	SoundEventImitateWither
	SoundEventImitateWitherSkeleton
	SoundEventImitateWolf
	SoundEventImitateZombie
	SoundEventImitateZombiePigman
	SoundEventImitateZombieVillager
	SoundEventEnderEyePlaced
	SoundEventEndPortalCreated
	SoundEventAnvilUse
	SoundEventBottleDragonBreath
	SoundEventPortalTravel
	SoundEventTridentHit
	SoundEventTridentReturn
	SoundEventTridentRiptide1
	SoundEventTridentRiptide2
	SoundEventTridentRiptide3
	SoundEventTridentThrow
	SoundEventTridentThunder
	SoundEventTridentHitGround
	SoundEventDefault
	SoundEventFletchingTableUse
	SoundEventElemConstructOpen
	SoundEventIceBombHit
	SoundEventBalloonPop
	SoundEventLtReactionIceBomb
	SoundEventLtReactionBleach
	SoundEventLtReactionElephantToothpaste
	SoundEventLtReactionElephantToothpaste2
	SoundEventLtReactionGlowStick
	SoundEventLtReactionGlowStick2
	SoundEventLtReactionLuminol
	SoundEventLtReactionSalt
	SoundEventLtReactionFertilizer
	SoundEventLtReactionFireball
	SoundEventLtReactionMagnesiumSalt
	SoundEventLtReactionMiscFire
	SoundEventLtReactionFire
	SoundEventLtReactionMiscExplosion
	SoundEventLtReactionMiscMystical
	SoundEventLtReactionMiscMystical2
	SoundEventLtReactionProduct
	SoundEventSparklerUse
	SoundEventGlowStickUse
	SoundEventSparklerActive
	SoundEventConvertToDrowned
	SoundEventBucketFillFish
	SoundEventBucketEmptyFish
	SoundEventBubbleColumnUpwards
	SoundEventBubbleColumnDownwards
	SoundEventBubblePop
	SoundEventBubbleUpInside
	SoundEventBubbleDownInside
	SoundEventHurtBaby
	SoundEventDeathBaby
	SoundEventStepBaby
	SoundEventSpawnBaby
	SoundEventBorn
	SoundEventTurtleEggBreak
	SoundEventTurtleEggCrack
	SoundEventTurtleEggHatched
	SoundEventLayEgg
	SoundEventTurtleEggAttacked
	SoundEventBeaconActivate
	SoundEventBeaconAmbient
	SoundEventBeaconDeactivate
	SoundEventBeaconPower
	SoundEventConduitActivate
	SoundEventConduitAmbient
	SoundEventConduitAttack
	SoundEventConduitDeactivate
	SoundEventConduitShort
	SoundEventSwoop
	SoundEventBambooSaplingPlace
	SoundEventPreSneeze
	SoundEventSneeze
	SoundEventAmbientTame
	SoundEventScared
	SoundEventScaffoldingClimb
	SoundEventCrossbowLoadingStart
	SoundEventCrossbowLoadingMiddle
	SoundEventCrossbowLoadingEnd
	SoundEventCrossbowShoot
	SoundEventCrossbowQuickChargeStart
	SoundEventCrossbowQuickChargeMiddle
	SoundEventCrossbowQuickChargeEnd
	SoundEventAmbientAggressive
	SoundEventAmbientWorried
	SoundEventCantBreed
	SoundEventShieldBlock
	SoundEventLecternBookPlace
	SoundEventGrindstoneUse
	SoundEventBell
	SoundEventCampfireCrackle
	SoundEventRoar
	SoundEventStun
	SoundEventSweetBerryBushHurt
	SoundEventSweetBerryBushPick
	SoundEventCartographyTableUse
	SoundEventStonecutterUse
	SoundEventComposterEmpty
	SoundEventComposterFill
	SoundEventComposterFillLayer
	SoundEventComposterReady
	SoundEventBarrelOpen
	SoundEventBarrelClose
	SoundEventRaidHorn
	SoundEventLoomUse
	SoundEventAmbientInRaid
	SoundEventUicartographyTableUse
	SoundEventUistonecutterUse
	SoundEventUiloomUse
	SoundEventSmokerUse
	SoundEventBlastFurnaceUse
	SoundEventSmithingTableUse
	SoundEventScreech
	SoundEventSleep
	SoundEventFurnaceUse
	SoundEventMooshroomConvert
	SoundEventMilkSuspiciously
	SoundEventCelebrate
	SoundEventJumpPrevent
	SoundEventAmbientPollinate
	SoundEventBeehiveDrip
	SoundEventBeehiveEnter
	SoundEventBeehiveExit
	SoundEventBeehiveWork
	SoundEventBeehiveShear
	SoundEventHoneybottleDrink
	SoundEventAmbientCave
	SoundEventRetreat
	SoundEventConvertToZombified
	SoundEventAdmire
	SoundEventStepLava
	SoundEventTempt
	SoundEventPanic
	SoundEventAngry
	SoundEventAmbientMoodWarpedForest
	SoundEventAmbientMoodSoulsandValley
	SoundEventAmbientMoodNetherWastes
	SoundEventAmbientMoodBasaltDeltas
	SoundEventAmbientMoodCrimsonForest
	SoundEventRespawnAnchorCharge
	SoundEventRespawnAnchorDeplete
	SoundEventRespawnAnchorSetSpawn
	SoundEventRespawnAnchorAmbient
	SoundEventSoulEscapeQuiet
	SoundEventSoulEscapeLoud
	SoundEventRecordPigstep
	SoundEventLinkCompassToLodestone
	SoundEventUseSmithingTable
	SoundEventEquipNetherite
	SoundEventAmbientLoopWarpedForest
	SoundEventAmbientLoopSoulsandValley
	SoundEventAmbientLoopNetherWastes
	SoundEventAmbientLoopBasaltDeltas
	SoundEventAmbientLoopCrimsonForest
	SoundEventAmbientAdditionWarpedForest
	SoundEventAmbientAdditionSoulsandValley
	SoundEventAmbientAdditionNetherWastes
	SoundEventAmbientAdditionBasaltDeltas
	SoundEventAmbientAdditionCrimsonForest
	SoundEventSculkSensorPowerOn
	SoundEventSculkSensorPowerOff
	SoundEventBucketFillPowderSnow
	SoundEventBucketEmptyPowderSnow
	SoundEventPointedDripstoneCauldronDripWater
	SoundEventPointedDripstoneCauldronDripLava
	SoundEventPointedDripstoneDripWater
	SoundEventPointedDripstoneDripLava
	SoundEventCaveVinesPickBerries
	SoundEventBigDripleafTiltDown
	SoundEventBigDripleafTiltUp
	SoundEventCopperWaxOn
	SoundEventCopperWaxOff
	SoundEventScrape
	SoundEventPlayerHurtDrown
	SoundEventPlayerHurtOnFire
	SoundEventPlayerHurtFreeze
	SoundEventUseSpyglass
	SoundEventStopUsingSpyglass
	SoundEventAmethystBlockChime
	SoundEventAmbientScreamer
	SoundEventHurtScreamer
	SoundEventDeathScreamer
	SoundEventMilkScreamer
	SoundEventJumpToBlock
	SoundEventPreRam
	SoundEventPreRamScreamer
	SoundEventRamImpact
	SoundEventRamImpactScreamer
	SoundEventSquidInkSquirt
	SoundEventGlowSquidInkSquirt
	SoundEventConvertToStray
	SoundEventCakeAddCandle
	SoundEventExtinguishCandle
	SoundEventAmbientCandle
	SoundEventBlockClick
	SoundEventBlockClickFail
	SoundEventSculkCatalystBloom
	SoundEventSculkShriekerShriek
	SoundEventWardenNearbyClose
	SoundEventWardenNearbyCloser
	SoundEventWardenNearbyClosest
	SoundEventWardenSlightlyAngry
	SoundEventRecordOtherside
	SoundEventTongue
	SoundEventCrackIronGolem
	SoundEventRepairIronGolem
	SoundEventUndefined
)

// LevelSoundEvent is sent by the server to make any kind of built-in sound heard to a player. It is sent to,
// for example, play a stepping sound or a shear sound. The packet is also sent by the client, in which case
// it could be forwarded by the server to the other players online. If possible, the packets from the client
// should be ignored however, and the server should play them on its own accord.
type LevelSoundEvent struct {
	SoundType             uint32
	Position              mgl32.Vec3
	ExtraData             int32
	EntityType            string
	BabyMob               bool
	DisableRelativeVolume bool
}

// ID ...
func (*LevelSoundEvent) ID() uint32 {
	return IDLevelSoundEvent
}

// Marshal ...
func (pk *LevelSoundEvent) Marshal(io protocol.IO) {
	io.Varuint32(&pk.SoundType)
	io.Vec3(&pk.Position)
	io.Varint32(&pk.ExtraData)
	io.String(&pk.EntityType)
	io.Bool(&pk.BabyMob)
	io.Bool(&pk.DisableRelativeVolume)
}
